name: Build and test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: 20
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: target/mvc-0.0.1-SNAPSHOT.jar
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: 20
        distribution: 'adopt'

    - uses: actions/download-artifact@v3
      with:
        name: my-app

    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
        npm install -g newman-reporter-allure
        npm install -g allure

    - name: run api app
      run: | 
        ls -lthra
        java -jar target/mvc-0.0.1-SNAPSHOT.jar &
        sleep 10
    - name: run newman test
      run: |
        newman run test/postman/students/students.json -e sample.json --reporters htmlextra,cli,allure --reporter-htmlextra-report sample.html

        ls -lthra

        
